project:
  type: website

website:
  title: "Li Wu"
  google-analytics: "G-5XKP5QW2FE"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: models/index.qmd
        text: Models        
      - href: discussion.qmd
        text: Discussion

  sidebar:
    - title: "Models"
      style: "docked"
      search: true
      collapse-level: 1
      contents:
        - models/index.qmd

        - section: "Static Pure Exchange Equilibrium Models"
          contents:
             - models/PureExch/MonopolisticSupply.qmd
             - models/PureExch/CommodityTaxUnderQuasilinearUtilityFunctions.qmd

        - section: "Static Production Equilibrium Models: Basic Models"
          contents:
            - models/ProdBasic/GeneralEquilibriumAndLinearProgramming.qmd
            - models/ProdBasic/MinimumWageAndEndogenousLaborSupply.qmd
        - section: "Static Production Equilibrium Models: Extended Models"
          contents:
            - models/ProdExtended/ProductionExternalityAndDegreeOneHomogenization.qmd
        
        - section: "Intertemporal Equilibrium Models: Basic Models"
          contents:
            - models/IntertemporalBasic/CanonicalDynamicMacroeconomicEquilibrium.qmd
            - models/IntertemporalBasic/ProductionOLGEquilibriumInTimelineForm.qmd

        - section: "Intertemporal Equilibrium Models: Extended Models"
          contents:
            - models/IntertemporalExtended/KnowledgeProduction.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

filters:
  - include-code-files

bibliography: references.bib
csl: harvard-cite-them-right.csl

nocite: |
#  @grandmont1977
