project:
  type: website

website:
  title: "Li Wu"
  google-analytics: "G-5XKP5QW2FE"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: models/index.qmd
        text: Models        
      - href: discussion.qmd
        text: Discussion

  sidebar:
    - title: "Models"
      style: "docked"
      search: true
      collapse-level: 1
      contents:
        - models/index.qmd

        - section: "Static Pure Exchange Equilibrium Models"
          contents:
            # - models/PureExch/index.qmd
             - models/PureExch/model1.qmd
             - models/PureExch/model2.qmd

        - section: "Static Production Equilibrium Models"
          contents:
             - models/Prod/model1.qmd
             - models/Prod/model2.qmd

        - section: "Intertemporal Equilibrium Models"
          contents:
            # - models/Intertemporal/model1.qmd
            # - models/Intertemporal/model2.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



